Security login fix
AkademiaProgramowania/project-planner pull request #19
Opened 2023-03-11 17:27 UTC by fngs101

1. Usunęłam z userEntity dziedziczenie po userze security. To było w mainie ale to były moje kombinacje przy security i wtedy zapomniałam to usunąć, to na razie nie jest potrzebne, może będzie jak będziemy łączyć usera z security.
2. Stworzyłam formularz logowania z użyciem sesji, nie wiem czy git ale tak z Danielem robiłam :D 
3. Działa wszystko git jeśli zrobi się permitAll zamiast tych wszystkich ograniczeń. Z ograniczeniami niestety się nie zalogujesz bo on z tym userem nie ma połączenia i tej roli nie wykrywa tam u niego.
4. Przy formularzu logowania jak zrobisz błąd typu złe hasło/zły email to security też nie pozwala na wyświetlenie tych błędów. Coś tam czytam w necie, ale nie do końca rozumiem, próbowałam mu wskazać że w przypadku błędu pokaż stronę ponownie, ale on ją odświeża czy nie wiem co robi (to ta linijka .failureUrl("/login")). Jak się to wyłączy to normalnie błędy się pokażą.

2023-03-26 12:28 UTC, fngs101 commented
-> auth.anyRequest().authenticated(); 
to nie pozwala na wejscie do konsoli bez logowania, nie pozwala też na przejscie do rejestracji bez logowania, wiec wyrzucilam 
ale moze wazne, nie do konca czaje to

->dodalam nowa stronke kiedy ktos nie ma na cos pozwolenia wtedy sie wyswietla, np developer nie ma prawa dodawac nowego taska

-> login jest z powrotem w naszym stylingu wczesniejszym

-> nowo powstały user z automatu dostaje role developera

-> dodalam tez do usera tworzonego password encoder bo bez tego nie odczytywał dobrze credentiali

-> sign in w index zamienione na sign out

2023-03-26 23:24 UTC, DrJul requested changes
trochę dużo zmian w różnych kontekstach jak na jednego pull rerquesta, na przyszłość lepiej podzielić np: osobny na obsługę strony z błędem, security, sesje

2023-03-26 23:24 UTC, DrJul commented on src/main/java/com/akademia/projectplanner/configuration/SecurityConfiguration.java
> +              auth.antMatchers("/registration").permitAll();
auth.anyRequest().authenticated() jest konieczne żeby zabezpieczyć się przed nieprzewidzianymi sytuacjami jak dodamy stronkę lub rolę i tego tutaj nie uwzględnimy przez pomyłkę. Dodając ten wymóg mamy pewność że jakiekolwiek zapytanie musi być wykonane przez sprawdzonego użytkownika

auth.antMatchers("/registration", "/console/**").permitAll(); 

coś takiego dodaj sobie zaraz na początku filtra i powinno działać zaraówno rejestracja jak i konsola, sprawdziłem ;)
w tych filtrach ważna jest kolejność, dlatego podajemy te zasoby od najbardziej ogólnych do restrykcyjnych

2023-03-26 23:24 UTC, DrJul commented on src/main/java/com/akademia/projectplanner/controller/LoginController.java
> +@AllArgsConstructor
potrzebny ten konstruktor?

2023-03-27 13:43 UTC, fngs101 commented
Merge request coś sugerował, że jest konflikt w RegistrationService, ale go raczej rozwiązałam. Gdyby coś to daj znać. 
Poza tym co zasugerowałeś to zmieniłam nazwę AuthorizationException na AuthenticationException (chyba tak to sie jednak powinno nazywać), wcześniej od Agnieszki było RegistrationException, ale korzystamy też z tego w LoginService gdzieś i chyba lepsza taka ogólna nazwa.

2023-03-27 22:12 UTC, DrJul approved these changes

2023-03-27 22:12 UTC, merged