Update README.md
AkademiaProgramowania/project-planner pull request #22
Opened 2023-04-03 14:23 UTC by fngs101

2023-04-03 14:24 UTC, fngs101 commented
Dodałabym jeszcze z screena z add task view, ale brakuje tam opcji przypisania do użytkownika. 
Trzeba dodać jak będzie ready.

2023-04-16 19:01 UTC, DrJul requested changes

2023-04-16 19:01 UTC, DrJul commented on README.md
> +Developed by [Juliusz](https://github.com/DrJul), [Agnieszka](https://github.com/Agnieszkaad77) and [Joanna](https://github.com/fngs101).
Dziękuję za uwzględnienie :) natomiast myślę, że bardziej uczciwie będzie jak zostawisz Waszą dwójkę jako zespół devowy. Kodu nie piszę poza wyjątkowymi sytuacjami tylko Was wspieram tutaj ;p

2023-04-19 19:46 UTC, DrJul approved these changes

2023-04-19 19:46 UTC, merged