Refactor method names. Add tests for TaskValidator
AkademiaProgramowania/project-planner pull request #26
Opened 2023-04-19 17:13 UTC by fngs101

Tak nieśmiało sobie coś napisałam w temacie testów. Postanowiłam też zmienić nazwy metod, jakoś mi nie pasowały potem w nazywaniu testów, mam nadzieję, że ok.

2023-04-19 20:39 UTC, DrJul requested changes

2023-04-19 20:39 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/validation/TaskValidatorTest.java
> +  @Test
Trochę poprawek stylistyczno-konwencyjnych, dotyczy całości:
- z tymi nazwami to nie powinniśmy powielać słowa "test" bo wiemy że to test, raczej stosuje się coś w stylu: shouldPassWith.. , throwExceptionWhenCośTam, ifArgumentIsCośTamToCośTam
- trochę opisowo ale nazwy testów czasami mogą być czytane przez devopsów, klientów itp w logach więc muszą być znaczące

  @Test
  void shouldBeFalseWithCorrectStatusAndName() {
    //given
    taskDto.setStatus("In progress");
    taskDto.setName("Task number 1");
    //when
    boolean result = TaskValidator.hasBlankNameOrStatus(taskDto);
    //then
    assertFalse(result);
  }

2023-04-19 20:39 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/validation/TaskValidatorTest.java
> +    taskDto.setStatus("");
jeszcze bym rozważył spację, co prawda używamy isBlank() ale jak ktoś w przyszłości zmieni to nie mamy takiego testu, dodaj w tym samym teście drugi taki sam obiekt tylko ze spacjami i zrób wiele asercji (może być assertAll)
- tylko nie nazywamy wtedy poprzez numerki tylko lepiej taskWithWhitespace / taskWithEmptyString lub coś w ten deseń

P.S jesli gdzieś jeszcze widzisz, że Twoim zdaniem można zamiast dwóch testów zrobić jeden ale z wieloma obiektami i asercjami to śmiało

2023-04-19 20:39 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/validation/TaskValidatorTest.java
> +    taskDto.setStatus("In progress");
a jeśli byśmy dostali np: "In regress"  to przejdzie - wydaje mi się, że trzeba by te statusy do enuma wyciągnąć ale to możemy przegadać jutro jeszcze jak to by zrobić

2023-04-20 16:12 UTC, fngs101 commented
Postanowiłam jednak zmienić te nazwy, bo w necie pisza żeby jednak nie umieszczać tego test i lepiej się to czyta jak faktycznie jest should. 
Dodałam test ze spacją.

2023-04-25 16:09 UTC, DrJul approved these changes

2023-04-25 16:09 UTC, merged