Tests to RegistrationValidator added
AkademiaProgramowania/project-planner pull request #29
Opened 2023-05-08 17:16 UTC by Agnieszkaad77

2023-05-08 17:21 UTC, Agnieszkaad77 commented
Dodałam też test rzucający wyjątek w przypadku utworzenia instancji RegistrationValidator, ale nie wiem czy koniecznie? Jeśli tak, to pewnie przydałoby się dorzucić też taki test w TaskValidator :)

2023-05-08 20:37 UTC, DrJul requested changes

2023-05-08 20:37 UTC, DrJul commented on src/main/java/com/akademia/projectplanner/validation/RegistrationValidator.java
> +  RegistrationValidator() {
wcześniej nie zwróciłem uwagi na to więc prośba o refaktor:
- usuń proszę ten throw exception i zostaw pusty konstruktor jako private (ze względu na statyczność metod)
- zrób testy do klasy klasę RegistrationServiceImpl gdzie rzucamy wyjątki: tak jak zrobiłaś test jest ok (sprawdzamy treść komunikatu) ale zrób jeszcze drugi test na samo rzucanie poprawnego exceptiona - wtedy z użyciem assertThrow :)

2023-05-08 20:37 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/validation/RegistrationValidatorTest.java
> +  private void createUserDto() {
tą klasę przesuń proszę na koniec klasy

2023-05-08 20:37 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/validation/RegistrationValidatorTest.java
> +  void shouldAssertFalseWhenRegistrationFieldsAreNonBlank() {
trochę się doczepię - podmień słówko Assert na Return
raczej nie spotkałem się by w nazwie testu używać "Assert", poza tym jest git

2023-05-08 20:37 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/validation/RegistrationValidatorTest.java
> +
testy są ok ale mamy tylko dwa na tzw happypath, dopisz proszę jeszcze na sytuacje gdy np: mamy jakieś pole ustawione na "" lub " ". Tutaj też dochodzi pytanie czy np przepuszczamy przykładowe hasło "-1", dobry temat więc poruszymy na weekly co z tym dalej :)

2023-05-22 21:30 UTC, Agnieszkaad77 commented
Zrobiłam zmiany, usunęłam wyjątek z konstruktora, dodałam dodatkowe testy. Ale pominęłam testy dla klasy RegistrationServiceImpl i te testy wyjątków tam, zrobię to już może na osobnym branchu :)

2023-05-24 21:05 UTC, DrJul requested changes

2023-05-27 18:12 UTC, Agnieszkaad77 commented
Ok, myślałam, że w przypadku testów też tak będzie dobrze, żeby nie powtarzać kodu :D 
Wyrzuciłam metodę i ustawiłam pola setami :)

2023-05-27 18:44 UTC, DrJul approved these changes

2023-05-27 18:44 UTC, merged