Add tests for task mapper. Remove unnecessary mport in LoginServiceImpl
AkademiaProgramowania/project-planner pull request #31
Opened 2023-05-15 15:33 UTC by fngs101

2023-05-21 19:11 UTC, DrJul requested changes
jedna techniczna uwaga tylko, poza tym ciężko się do czegoś przyczepić ;)

2023-05-21 19:11 UTC, DrJul commented on src/test/java/com/akademia/projectplanner/mapper/TaskMapperTest.java
> +    MockitoAnnotations.openMocks(this);
co prawda testy przechodzą ale jeśli chcemy używać openMocks() w sposób prawilny to powinniśmy jeszcze zamknąć mocki po każdym z testów:
https://javastart.pl/baza-wiedzy/testowanie-jednostkowe/mockito-tworzenie-mockow
pod hasłem: "Adnotacja @Mock i MockitoAnnotations.openMocks()"

osobiście nawet tego nigdy nie stosowałem tylko poprzez adnotację @ExtendWith(MockitoExtension.class),
więc fajny przykład się trafił :)

2023-05-22 16:03 UTC, fngs101 commented
Good to know, nigdy ich nie zamykałam dotychczas 🙈 XD

2023-05-24 20:55 UTC, DrJul approved these changes

2023-05-24 20:55 UTC, merged