Create a map task-user and send it to the model to display user email…
AkademiaProgramowania/project-planner pull request #32
Opened 2023-05-27 12:02 UTC by fngs101

… under the task name

Nie miałam innego pomysłu niż mapa zamiast listy którą wysyłamy w homeController.
Jeśli tak jest ok to jedna rzecz mnie zastanawia: 
czy może w getMainPage w kontrolerze już nie robić tej listy wszystkich tasków z serwisu, niech to może będzie prywatna metoda w tym serwisie i można ją całkiem usunąć z kontrolera? 
Jeśli nie jest ok to podyskutujemy czy nie było lepszej możliwości niż mapa. :)

2023-05-28 21:41 UTC, DrJul requested changes

2023-05-30 16:49 UTC, fngs101 commented
Ok ready. 
Ale dodam tez task do trello żeby defaultowo żaden user nie był przypisany, tak jak mówiłeś.

2023-05-30 21:14 UTC, DrJul requested changes

2023-05-30 21:14 UTC, DrJul commented on src/main/java/com/akademia/projectplanner/controller/HomeController.java
> +    model.addAttribute("taskWithEmails", taskWithEmails);
tutaj tylko bym dla zasady zmienił na - tasksWithEmails - w sensie  że mamy więcej niż jednego taska ;)

2023-05-31 13:32 UTC, fngs101 commented
Sorry za ten brain fart, za szybko to puściłam :D

2023-06-02 17:35 UTC, DrJul approved these changes

2023-06-02 17:37 UTC, DrJul requested changes
rozwiąż proszę konflikty bo się pojawiły ;)

2023-06-12 14:54 UTC, fngs101 commented
done

2023-06-18 17:20 UTC, DrJul approved these changes

2023-06-18 17:20 UTC, merged