Unassigned user
AkademiaProgramowania/project-planner pull request #34
Opened 2023-06-18 18:26 UTC by fngs101

Trochę się zastanawiałam nad tymi checkami w taskmaperze jak to powinno być, poszłam za następującą logiką: 
-> zostawiłam metodę getUser gdzie jest error rzucany kiedy nie ma takiego ID w repo, no bo jednak jakby dostał ID 4, a nie byłoby takiego w repo to chcemy mieć błąd. Zmodyfikowałam zatem test odpowiedni żeby po prostu zwracał empty usera przy randomowym IDku. Tutaj właśnie nie wiem czy tak to powinno być
-> zmodyfikowałam za to getUserId bo tam było sprawdzanie czy user jest nullem na początku i throw do tego, to tej części już raczej nie chcemy, dlatego też wyrzuciłam test do tego.
Proszę o spojrzenie 🙏

2023-06-20 20:53 UTC, DrJul requested changes
hej, trochę nad tym myślałem ale myślę, że tak jest ok, wszystkie założenia są spełnione, jedynie mały komentarz co do konwencji mam :)

2023-06-20 20:53 UTC, DrJul commented on src/main/java/com/akademia/projectplanner/service/impl/TaskServiceImpl.java
> +        email = "unassigned";
wyciągnąć do osobnego pola w klasie np:
private static final String UNASSIGNED = "unassigned";

polecam konwecję gdzie stałe Stringowe mamy zapisane jako pola w klasie, kod jest bardziej przejrzysty i łatwiej zmieniać teksty (nie trzeba szukać po całym projekcie/klasie) - w naszym projekcie nie ma tego aż tyle ale i tak dobrze już sobie takie nawyki robić

2023-06-25 08:41 UTC, fngs101 commented
Racja, done :)

2023-06-25 21:18 UTC, DrJul approved these changes

2023-06-25 21:18 UTC, merged